[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
  lineNos = true
  lineNumbersInTable = false

[params.theme.font.google]
  heading = "Crimson Pro"
  body = "Source Sans 3"
  code = "Source Code Pro"
  arabic = "Amiri"
